<?php
$menu['menu600'] = array(
    array('600000', '리소스 관리', '' . G5_ADMIN_URL . '/rsc_review_list.php', 'rsc_review_list'),
    array('600000', '사이트메인 관리', '' . G5_ADMIN_URL . '/rsc_main_banner_mng.php', 'rsc_main_banner_mng', 1),
    array('600950', '메인 비쥬얼관리', '' . G5_ADMIN_URL . '/rsc_main_banner_mng.php', 'rsc_main_banner_mng'),
    array('600960', '메인 새소식관리', '' . G5_ADMIN_URL . '/rsc_main_news_mng.php', 'rsc_main_news_mng'),
    array('600970', '메인 리소스관리', '' . G5_ADMIN_URL . '/rsc_main_res_mng.php', 'rsc_main_res_mng'),
    array('600000', '새소식', '' . G5_ADMIN_URL . '/rsc_news_list.php', 'rsc_news_list', 1),
    array('600700', '새소식 관리', '' . G5_ADMIN_URL . '/rsc_news_list.php', 'rsc_news_list'),
    array('600000', '이벤트', G5_ADMIN_URL . '/rsc_event_list.php?sub_menu=600980', 'rsc_event_list', 1),
    array('600980', '이벤트 관리', G5_ADMIN_URL . '/rsc_event_list.php?sub_menu=600980', 'rsc_event_list'),
    array('600990', '글로벌 이벤트 관리', '' . G5_ADMIN_URL . '/rsc_global_event_list.php', 'rsc_global_event_list'),
    array('600000', '배너 통합 관리', '' . G5_ADMIN_URL . '/rsc_banner_mng.php', 'rsc_banner_mng', 1),
    array('600900', '배너 통합 관리', '' . G5_ADMIN_URL . '/rsc_banner_mng.php', 'rsc_banner_mng'),
    array('600000', '다시보기', '' . G5_ADMIN_URL . '/rsc_review_mng.php', 'rsc_review_mng', 1),
    array('600100', '리소스 카테고리 관리', '' . G5_ADMIN_URL . '/rsc_review_mng.php', 'rsc_review_mng'),
    array('600200', '리소스 관리', '' . G5_ADMIN_URL . '/rsc_review_list.php', 'rsc_review_list'),
    array('600000', '무료콘텐츠', '' . G5_ADMIN_URL . '/rsc_free_mng.php', 'rsc_free_mng', 1),
    array('600300', '리소스 카테고리 관리', '' . G5_ADMIN_URL . '/rsc_free_mng.php', 'rsc_free_mng'),
    array('600400', '리소스 관리', '' . G5_ADMIN_URL . '/rsc_free_list.php', 'rsc_free_list'),
    array('600000', '백서', '' . G5_ADMIN_URL . '/rsc_book_mng.php', 'rsc_book_mng', 1),
    array('600500', '리소스 카테고리 관리', '' . G5_ADMIN_URL . '/rsc_book_mng.php', 'rsc_book_mng'),
    array('600600', '리소스 관리', '' . G5_ADMIN_URL . '/rsc_book_list.php', 'rsc_book_list'),
);
?>